### PR TITLE
Allow external reference to type StoreSelectedScope

### PR DESCRIPTION
**Pull request by fcorreapfl**
## Description
Moved class `StoreSelectedScope` from `VirtoCommerce.StoreModule.Web.Authorization` to `VirtoCommerce.StoreModule.Data.Authorization` so that it can be referenced by external modules when doing validations against permissions that are scoped by StoreId using this type.

With this type being sealed in the Web project it is impossible to create new auth handlers that can do additional checks against permissions that use this type of scope. Moving it to the Data project is a simple fix that at least gives some flexibility to expand the permissions model.

### CODE REVIEW

**Comment by fcorreapfl** [comment]
I followed this guide: https://www.virtocommerce.org/t/how-to-contribute-to-virto-commerce/459 which explicitly mentions all the work should be done based off of `master`, however seeing there are 19 additional commits and the message up there "Merge the latest changes from dev into this branch." makes me think it should have all been done based off of `dev`. 

Please let me know how to proceed so that this can move forward as fast as possible.

**Comment by fcorreapfl** [comment]
Also, about the CLA, I have signed it and this is what is shown when I click details:
image

It also shows on the list of my CLAs:
image

I don't understand why it still shows as pending above.

**Review by OlegoO — CHANGES_REQUESTED** [review]
@fcorreapfl Could you move StoreSelectedScope to Core project and VirtoCommerce.StoreModule.Core.Security namespac? Because you don't need anything from Data assembly and it will be related to VirtoCommerce.Platform.Core.Security.PermissionScope.

**Comment by fcorreapfl** [comment]
@OlegoO Thank you for the comments. I just applied the change, please let me know if anything else would be needed.

**Review by OlegoO — APPROVED** [review]

**Comment by fcorreapfl** [comment]
@OlegoO Saw the new release up, just in case you want to fix the release notes, I see they are referencing what I put in the description of the PR but it changed due to your comment: https://github.com/VirtoCommerce/vc-module-store/releases/tag/3.210.0

Release notes as they are could be confusing for people without the context of this PR.

Thank you very much for helping move this forward.

**Comment by OlegoO** [comment]
@fcorreapfl  I fixed the release note. thx.

**Pull request merged**
